### ISSUE TITLE
for how long the dev fee will last?

### ISSUE THREAD

**Issue by Aprrentice** [MoneroOcean/xmr-node-proxy#125]
am sure this was asked many times. but just noticed this when checking the proxy over http and it has been there for like 1h30min.
it is the first time I notice it and I do not think this is normal.

![image](https://user-images.githubusercontent.com/41146763/78115400-71be9880-740b-11ea-8df5-56b141680cec.png)

**Comment by Aprrentice** [comment]
This happening again. Been already for am hour.

![IMG_20200402_004849](https://user-images.githubusercontent.com/41146763/78190047-e3cec600-747b-11ea-94c0-12508c2b3209.jpg)

**Comment by MoneroOcean** [comment]
Normally it should be below developerShare percent amount for unlimited amount of time. It can became more if you have not so big amount of miners so they can not be divided in such a way that at least of them is hashing below developerShare. I recommend to set developerShare to 0 in that case or if you still want to donate add %1%44qJYxdbuqSKarYnDSXB6KLbsH4yR65vpJe3ELLDii9i4ZgKpgQXZYR4AMJxBJbfbKZGWUxZU42QyZSsP4AyZZMbJBCrWr1 to the end of your XMR address in "username" in config.json. %1% will forward 1% of hashrate to 44qJYxdbuqSKarYnDSXB6KLbsH4yR65vpJe3ELLDii9i4ZgKpgQXZYR4AMJxBJbfbKZGWUxZU42QyZSsP4AyZZMbJBCrWr1 donation address and it will be precisely 1% despite number of your miners since it is done on pool side.
