### ISSUE TITLE
Working with CN Universal and other pools.

### ISSUE THREAD

**Issue by 7evenmikser** [MoneroOcean/xmr-node-proxy#53]
Hello! 
As far as I know XNP works ONLY with nodeJS pool. Is there any chance to let him work with CN Universal pool and other pools?

Or at least does MoneroOcean going to launch more pools with other coins? There are tons of coins on CN, CN-lite, CN-heavy, etc algos and even if XNP supports them, there are almost no chance to mine them...

Thanks!

**Comment by MoneroOcean** [comment]
I do not want to put effort in improving other pool software since it will take too much time to learn/implement and test. For MoneroOcean I have near future plans to add cn-heave/cn-light mining (with all coin variants) via patched xmrig (MO pool support is 90% ready as well). See https://github.com/xmrig/xmrig/pull/719
AMD/nVidia xmrig versions will follow. If it will be notintegrated into upstream xmrig I will maintain my own patched forks of xmrig sources.

**Comment by MoneroOcean** [comment]
Experimental multi algo coin mining is enabled on fr.moneroocean.stream node. You need to build patched xmrig/xmrig-amd from https://github.com/MoneroOcean/xmrig and https://github.com/MoneroOcean/xmrig-amd for that at this moment.
